### ISSUE TITLE
Requirements update

### ISSUE THREAD

**Issue by mwolff44** [panosl/django-currencies#42]
Hi,

As the openexchange is needed, you need to install openexchangerates package (pip install openexchangerates).
Could you update the doc ?
Also, i try to import json file containing devices definition, but i have got this error : 

`python manage.py loaddata /usr/local/venv/local/lib/python2.7/site-packages/currencies/management/commands/currencies.json
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 60, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 100, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 152, in load_label
    for obj in objects:
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/core/serializers/json.py", line 85, in Deserializer
    six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2])
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/core/serializers/json.py", line 79, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/core/serializers/python.py", line 96, in Deserializer
    Model = _get_model(d["model"])
django.core.serializers.base.DeserializationError: Problem installing fixture '/usr/local/venv/local/lib/python2.7/site-packages/currencies/management/commands/currencies.json': string indices must be integers
`

**Comment by einarf** [comment]
Theres some issues with the openexchangerates package. The project seems to be abandoned, so I suggested recently to include that module in this project as well to eliminate the dependency. The main problem with openexchangerates is that it doesn't work in python 3.

The error you describe here doesn't look familiar though. What does the `currencies.json` file contain?

**Comment by panosl** [comment]
I don't mind including openexchangerates in here if somebody where to manage that part. Bring it in!

**Comment by racitup** [comment]
Latest master now has a python3-compatible fork of the oxr client builtin :)
